export enum NotificationType {
  COMPANY_PENDING = 'COMPANY_PENDING',
  PRODUCT_PENDING = 'PRODUCT_PENDING',
  PRODUCT_APPROVED = 'PRODUCT_APPROVED',
  PRODUCT_REJECTED = 'PRODUCT_REJECTED',
  PRODUCT_LOW_STOCK = 'PRODUCT_LOW_STOCK',
  PRODUCT_SOLD_OUT = 'PRODUCT_SOLD_OUT',
  PRODUCT_AUTO_DELETED = 'PRODUCT_AUTO_DELETED',
  ORDER_UPDATED = 'ORDER_UPDATED',
  NEW_ORDER = 'NEW_ORDER',
  DELIVERY_ASSIGNED = 'DELIVERY_ASSIGNED',
  DRIVER_RATED = 'DRIVER_RATED',
}
