export enum NotificationType {
  COMPANY_PENDING = 'COMPANY_PENDING',
  PRODUCT_PENDING = 'PRODUCT_PENDING',
  PRODUCT_APPROVED = 'PRODUCT_APPROVED',
  PRODUCT_REJECTED = 'PRODUCT_REJECTED',
  ORDER_UPDATED = 'ORDER_UPDATED',
  NEW_ORDER = 'NEW_ORDER',
  DELIVERY_ASSIGNED = 'DELIVERY_ASSIGNED',
  DRIVER_RATED = 'DRIVER_RATED',
}
